import { useState, useEffect } from 'react'
import {
  Box,
  Typography,
  Button,
  Alert,
  CircularProgress,
  Card,
  CardContent,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  TextField,
} from '@mui/material'
import {
  Telegram as TelegramIcon,
  Link as LinkIcon,
  CheckCircle as CheckIcon,
  ContentCopy as CopyIcon,
} from '@mui/icons-material'
import { useAuth } from '../hooks/useAuth'
import { supabase } from '../lib/supabase'

interface TelegramLink {
  telegram_id: number
  telegram_username: string | null
  telegram_first_name: string | null
  telegram_last_name: string | null
  is_verified: boolean
}

function generateCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  let code = ''
  for (let i = 0; i < 6; i++) {
    code += chars[Math.floor(Math.random() * chars.length)]
  }
  return code
}

export default function Settings() {
  const { user } = useAuth()
  const [telegramLink, setTelegramLink] = useState<TelegramLink | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)

  // Code generation
  const [linkCode, setLinkCode] = useState<string | null>(null)
  const [codeLoading, setCodeLoading] = useState(false)
  const [copied, setCopied] = useState(false)

  // Code entry
  const [showEnterCodeDialog, setShowEnterCodeDialog] = useState(false)
  const [enterCode, setEnterCode] = useState('')
  const [enterCodeLoading, setEnterCodeLoading] = useState(false)

  useEffect(() => {
    if (user) {
      loadTelegramLink()
    }
  }, [user])

  const loadTelegramLink = async () => {
    if (!user) return

    setLoading(true)
    setError(null)

    try {
      const { data, error: fetchError } = await supabase
        .from('telegram_auth_links')
        .select('*')
        .eq('user_id', user.id)
        .single()

      if (fetchError && fetchError.code !== 'PGRST116') {
        throw fetchError
      }

      setTelegramLink(data || null)
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Ошибка загрузки'
      setError(message)
    } finally {
      setLoading(false)
    }
  }

  // Generate a code for the Telegram user to enter
  const handleGenerateCode = async () => {
    if (!user) return

    setCodeLoading(true)
    setError(null)
    setSuccess(null)

    try {
      // Delete any existing codes for this user
      await supabase
        .from('linking_codes')
        .delete()
        .eq('user_id', user.id)

      const code = generateCode()

      const { error: insertError } = await supabase
        .from('linking_codes')
        .insert({
          code,
          user_id: user.id,
          platform: 'web',
        })

      if (insertError) throw insertError

      setLinkCode(code)
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Ошибка генерации кода'
      setError(message)
    } finally {
      setCodeLoading(false)
    }
  }

  const handleCopyCode = async () => {
    if (!linkCode) return
    try {
      await navigator.clipboard.writeText(linkCode)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback
    }
  }

  // Enter a code generated by the Telegram user
  const handleEnterCode = async () => {
    if (!user || !enterCode.trim()) return

    setEnterCodeLoading(true)
    setError(null)
    setSuccess(null)

    try {
      const { data, error: rpcError } = await supabase
        .rpc('link_accounts', {
          p_code: enterCode.trim().toUpperCase(),
          p_current_user_id: user.id,
        })

      if (rpcError) throw rpcError

      const result = data as { success: boolean; error?: string; quizzes_moved?: number }

      if (!result.success) {
        setError(result.error || 'Неизвестная ошибка')
        return
      }

      setSuccess(`Аккаунты связаны! Перенесено викторин: ${result.quizzes_moved || 0}`)
      setEnterCode('')
      setShowEnterCodeDialog(false)
      loadTelegramLink()
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Ошибка при привязке'
      setError(message)
    } finally {
      setEnterCodeLoading(false)
    }
  }

  const handleUnlinkTelegram = async () => {
    if (!confirm('Отвязать Telegram аккаунт?')) return

    try {
      const { error: deleteError } = await supabase
        .from('telegram_auth_links')
        .delete()
        .eq('user_id', user!.id)

      if (deleteError) throw deleteError

      setTelegramLink(null)
      setLinkCode(null)
      setSuccess('Telegram аккаунт отвязан')
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Ошибка при отвязке'
      setError(message)
    }
  }

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', mt: 8 }}>
        <CircularProgress />
      </Box>
    )
  }

  return (
    <Box sx={{ maxWidth: 800, mx: 'auto' }}>
      <Typography variant="h3" component="h1" gutterBottom>
        Настройки
      </Typography>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }} onClose={() => setError(null)}>
          {error}
        </Alert>
      )}
      {success && (
        <Alert severity="success" sx={{ mb: 3 }} onClose={() => setSuccess(null)}>
          {success}
        </Alert>
      )}

      {/* Account info */}
      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            Аккаунт
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Email: {user?.email}
          </Typography>
        </CardContent>
      </Card>

      {/* Telegram linking */}
      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
            <Typography variant="h6">
              Telegram аккаунт
            </Typography>
            {telegramLink?.is_verified ? (
              <Chip icon={<CheckIcon />} label="Привязан" color="success" size="small" />
            ) : (
              <Chip icon={<LinkIcon />} label="Не привязан" color="default" size="small" />
            )}
          </Box>

          {telegramLink?.is_verified ? (
            <Box>
              {telegramLink.telegram_username && (
                <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                  Username: @{telegramLink.telegram_username}
                </Typography>
              )}
              <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                {telegramLink.telegram_first_name} {telegramLink.telegram_last_name}
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                Аккаунт привязан. Ваши викторины синхронизированы с Telegram Mini App.
              </Typography>
              <Button
                variant="outlined"
                color="error"
                onClick={handleUnlinkTelegram}
              >
                Отвязать Telegram
              </Button>
            </Box>
          ) : (
            <Box>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Привяжите Telegram, чтобы видеть свои викторины в Telegram Mini App
              </Typography>

              {/* Option 1: Generate code */}
              <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }}>
                Вариант 1: Сгенерировать код
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                Создайте код и введите его в Telegram Mini App (Настройки → Ввести код)
              </Typography>

              {linkCode ? (
                <Box sx={{ mb: 3 }}>
                  <Box sx={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: 1,
                    p: 2,
                    borderRadius: 2,
                    backgroundColor: 'rgba(99, 102, 241, 0.1)',
                    border: '2px dashed #6366f1',
                    mb: 1,
                  }}>
                    <Typography variant="h4" sx={{
                      fontWeight: 'bold',
                      letterSpacing: '0.3em',
                      fontFamily: 'monospace',
                    }}>
                      {linkCode}
                    </Typography>
                    <Button
                      size="small"
                      startIcon={<CopyIcon />}
                      onClick={handleCopyCode}
                    >
                      {copied ? 'Скопировано!' : 'Копировать'}
                    </Button>
                  </Box>
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', textAlign: 'center' }}>
                    Код действителен 10 минут
                  </Typography>
                  <Button
                    variant="outlined"
                    fullWidth
                    onClick={handleGenerateCode}
                    sx={{ mt: 1 }}
                    size="small"
                  >
                    Создать новый код
                  </Button>
                </Box>
              ) : (
                <Button
                  variant="contained"
                  startIcon={<TelegramIcon />}
                  onClick={handleGenerateCode}
                  disabled={codeLoading}
                  sx={{ mb: 3 }}
                >
                  {codeLoading ? <CircularProgress size={24} color="inherit" /> : 'Создать код привязки'}
                </Button>
              )}

              {/* Option 2: Enter code from Telegram */}
              <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }}>
                Вариант 2: Ввести код из Telegram
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                Если вы получили код в Telegram Mini App, введите его здесь
              </Typography>
              <Button
                variant="outlined"
                startIcon={<LinkIcon />}
                onClick={() => setShowEnterCodeDialog(true)}
              >
                Ввести код
              </Button>
            </Box>
          )}
        </CardContent>
      </Card>

      {/* Enter code dialog */}
      <Dialog open={showEnterCodeDialog} onClose={() => setShowEnterCodeDialog(false)}>
        <DialogTitle>Ввести код привязки</DialogTitle>
        <DialogContent>
          <DialogContentText sx={{ mb: 2 }}>
            Введите 6-значный код из Telegram Mini App
          </DialogContentText>
          <TextField
            fullWidth
            label="Код привязки"
            value={enterCode}
            onChange={(e) => setEnterCode(e.target.value.toUpperCase())}
            disabled={enterCodeLoading}
            placeholder="ABC123"
            inputProps={{ maxLength: 6, style: { letterSpacing: '0.2em', textAlign: 'center', fontSize: '1.5em' } }}
            autoFocus
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShowEnterCodeDialog(false)}>
            Отмена
          </Button>
          <Button
            onClick={handleEnterCode}
            disabled={enterCodeLoading || enterCode.length < 6}
            variant="contained"
          >
            {enterCodeLoading ? <CircularProgress size={24} /> : 'Привязать'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
